version: "3.3"
services:
  rabbitmq-stats:
    image: docker.io/bitnami/rabbitmq:3.8
    environment:
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbit@rabbitmq-stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_SECURE_PASSWORD=yes
    volumes:
      - ./data/rabbitmq/custom.conf:/bitnami/rabbitmq/conf/custom.conf:z
    ports:
      - '15672:15672'
      - '5672:5672'
  mongodb-primary:
    image: docker.io/bitnami/mongodb:4.4
    volumes:
      - ./data/mongo-data:/bitnami/mongodb:z
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_USERNAME=cteadmin
      - MONGODB_PASSWORD=cteadmin
      - MONGODB_DATABASE=cte
    ports:
      - '27017:27017'
  core:
    image: docker.io/crestsystems/netskope:core-latest-dev
    volumes:
      - ./data/custom_plugins:/opt/netskope/plugins/custom_plugins:z
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MONGO_CONNECTION_STRING=mongodb://cteadmin:cteadmin@mongodb-primary:27017/cte
      - RABBITMQ_CONNECTION_STRING=amqp://user:bitnami@rabbitmq-stats
      - JWT_SECRET=secret
      - JWT_ALGORITHM=HS256
      - ENABLE_CELERY_BEAT=true
      - DOCKER_USERNAME=DOCKER_USERNAME
      - DOCKER_PASSWORD=DOCKER_PASSWORD
      - WATCHTOWER_HTTP_API_TOKEN=token
      - ANALYTICS_BASE_URL=http://localhost
      - ANALYTICS_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpbnN0YWxsYXRpb25faWQiOiJjMDAyIn0.w8SVrTcDjk8PkR4IcbWGwOyf6-OWfCUyOoCTgZvqHqc
    restart: on-failure:5
    depends_on:
      - mongodb-primary
      - rabbitmq-stats
    labels:
      - com.centurylinklabs.watchtower.enable=true
  ui:
    image: docker.io/crestsystems/netskope:ui-latest-dev
    restart: on-failure:5
    environment:
      - CE_API_URL=http://core
    volumes:
      - ./data/ssl_certs:/tmp/ssl_certs:z
    ports:
      - 443:3000
    links:
      - core
    labels:
      - com.centurylinklabs.watchtower.enable=true
  watchtower:
    image: containrrr/watchtower:1.0.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json  # uncomment this line if repo requires authentication
    environment:
      - WATCHTOWER_HTTP_API=true
      - WATCHTOWER_HTTP_API_TOKEN=token
      - WATCHTOWER_LABEL_ENABLE=true
    ports:
      - 8080:8080
    command: --interval 30 {"mode":"full","isActive":false}
