version: "3"
services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    command: [--auth]
    volumes:
      - ./mongo-user:/docker-entrypoint-initdb.d:z
    environment:
      - MONGO_INITDB_ROOT_USERNAME=cteadmin
      - MONGO_INITDB_ROOT_PASSWORD=cteadmin
    restart: on-failure:5
    ports:
      - 27017:27017
  core:
    image: shivangcrest/netskope_cte:core-S4-1.0.0_13
    container_name: "core"
    volumes:
      - ./custom_plugins:/opt/cte/custom_plugins
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USER=cteadmin
      - MONGO_PASSWORD=cteadmin
      - RABBITMQ_HOST=localhost
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - JWT_SECRET=secret
      - JWT_ALGORITHM=HS256
    restart: on-failure:5
    ports:
      - 8080:80 # for gunicorn
      - 15672:15672 # for rabbitmq management plugin
    links:
      - mongodb
  ui:
    image: shivangcrest/netskope_cte:ui-S4-1.0.0_10
    container_name: "ui"
    restart: on-failure:5
    ports:
      - 3000:3000
    links:
      - core
