version: '3'
services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    command: [--auth]
    environment:
    - MONGO_INITDB_ROOT_USERNAME=cteadmin
    - MONGO_INITDB_ROOT_PASSWORD=cteadmin
    ports:
    - 27017:27017