version: '3'
services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    command: [--auth]
    environment:
    - MONGO_INITDB_ROOT_USERNAME=cteadmin
    - MONGO_INITDB_ROOT_PASSWORD=cteadmin
    ports:
    - 27017:27017
  core:
    image: 10.0.9.93:5000/cte:core
    container_name: "core"
    environment:
    - MONGO_HOST=mongodb
    - MONGO_PORT=27017
    - MONGO_USER=cteadmin
    - MONGO_PASSWORD=cteadmin
    - RABBITMQ_HOST=localhost
    - RABBITMQ_USER=guest
    - RABBITMQ_PASSWORD=guest
    - JWT_SECRET=blank
    - JWT_ALGORITHM=blank
    ports:
    - 8080:80  # for gunicorn
    - 15672:15672  # for rabbitmq management plugin
    links:
    - mongodb
  ui:
    image: 10.0.9.93:5000/cte:ui
    container_name: "ui"
    ports:
    - 3000:3000
    links:
    - core